/** @type {import('cz-git').CommitizenGitOptions} */
export default {
  alias: { fd: 'docs: fix typos' },
  messages: {
    type: '选择你要提交的类型 :',
    scope: '选择一个提交范围（可选）:',
    customScope: '请输入自定义的提交范围 :',
    subject: '填写简短精炼的变更描述 :\n',
    body: '填写更加详细的变更描述（可选）。使用 \'|\' 换行 :\n',
    breaking: '列举非兼容性重大的变更（可选）。使用 \'|\' 换行 :\n',
    footerPrefixesSelect: '选择关联issue前缀（可选）:',
    customFooterPrefix: '输入自定义issue前缀 :',
    footer: '列举关联issue (可选) 例如: #31, #I3244 :\n',
    confirmCommit: '是否提交或修改commit ?',
  },
  types: [
    { value: '新增', name: '新增:    新增功能 | A new feature', emoji: ':sparkles:' },
    { value: '修复', name: '修复:    修复缺陷 | A bug fix', emoji: ':bug:' },
    { value: '文档', name: '文档:    文档更新 | Documentation only changes', emoji: ':memo:' },
    { value: '格式', name: '格式:    代码格式 | Changes that do not affect the meaning of the code', emoji: ':lipstick:' },
    { value: '重构', name: '重构:    代码重构 | A code change that neither fixes a bug nor adds a feature', emoji: ':recycle:' },
    { value: '性能', name: '性能:    性能提升 | A code change that improves performance', emoji: ':zap:' },
    { value: '测试', name: '测试:    测试相关 | Adding missing tests or correcting existing tests', emoji: ':white_check_mark:' },
    { value: '构建', name: '构建:    构建相关 | Changes that affect the build system or external dependencies', emoji: ':package:' },
    { value: '集成', name: '集成:    持续集成 | Changes to our CI configuration files and scripts', emoji: ':ferris_wheel:' },
    { value: '其他', name: '其他:    其他修改 | Other changes that don\'t modify src or test files', emoji: ':hammer:' },
    { value: '回退', name: '回退:    回退代码 | Reverts a previous commit', emoji: ':rewind:' },
  ],
  useEmoji: true,
  emojiAlign: 'center',
  useAI: false,
  aiNumber: 1,
  themeColorCode: '',
  scopes: [],
  allowCustomScopes: true,
  allowEmptyScopes: true,
  customScopesAlign: 'bottom',
  customScopesAlias: 'custom',
  emptyScopesAlias: 'empty',
  upperCaseSubject: false,
  markBreakingChangeMode: false,
  allowBreakingChanges: ['新增', '修复'],
  breaklineNumber: 100,
  breaklineChar: '|',
  skipQuestions: [],
  issuePrefixes: [{ value: 'closed', name: 'closed:   标记 ISSUES 已完成' }],
  customIssuePrefixAlign: 'top',
  emptyIssuePrefixAlias: 'skip',
  customIssuePrefixAlias: 'custom',
  allowCustomIssuePrefix: true,
  allowEmptyIssuePrefix: true,
  confirmColorize: true,
  minSubjectLength: 0,
  defaultBody: '',
  defaultIssues: '',
  defaultScope: '',
  defaultSubject: '',
};
