/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgreePrivacy: typeof import('./../src/components/agree-privacy/agree-privacy.vue')['default']
    Card: typeof import('./../src/components/card/card.vue')['default']
    Login: typeof import('./../src/components/login/login.vue')['default']
    Map: typeof import('./../src/components/map/map.vue')['default']
    Tabbar: typeof import('./../src/components/tabbar/tabbar.vue')['default']
  }
}
